### PR TITLE
fix GetRouteByHandler to return the route reference and permits to mo…

### PR DESCRIPTION
**Pull request by snigle**
…dify description

### CODE REVIEW

**Comment by wI2L** [comment]
@snigle What is the rationale behind this change proposal ? I understand that you want to update the description of the route afterhand but why involve tonic in it ? Are you using https://github.com/wI2L/fizz with it or the old swagger package ?

**Comment by snigle** [comment]
I'm using the swagger generator from the documentation : 
https://github.com/loopfz/gadgeto/blob/master/tonic/README#L133

**Comment by wI2L** [comment]
Please use https://github.com/loopfz/gadgeto/blob/66ad4638c25c77275b47b89dd23d013c36aaae48/tonic/tonic.go#L200 as a parameter of `tonic.Handler()` when you declare your route to feed in the description.
@loopfz your thoughts ? looks like a non-issue to me.

**Comment by loopfz** [comment]
A bit late, but I agree

**Pull request closed without merging**
