### PR TITLE
 fix: make sure a validator exists

### PR DESCRIPTION
**Pull request by hmajid2301**
In the RegisterTagNameFunc make sure the validator exists,
before trying to assign a func to it. Also updated comment to fix small typos.

### CODE REVIEW

**Comment by hmajid2301** [comment]
Any update on this PR ?

**Comment by hmajid2301** [comment]
Hi any update on this ?

**Review by sgburtsev — APPROVED** [review]
I've fixed it in the same way.

**Comment by mcorbin** [comment]
I'm also interested by this fix. 
@loopfz what do you think about it ?

**Review by wI2L — APPROVED** [review]

**Pull request merged**
